/**
 * First-run seed. Real TrackMan sessions come from data/seed/sessions.json
 * (generated by scripts/import-trackman.mjs). Rounds, lessons, goals and
 * blueprint text are EXAMPLES flagged source:'example' until real ones replace them.
 */
import { db } from './index.js';
import { PLAYER_ID } from './repo.js';
import trackman from '../../data/seed/sessions.json';

export async function seedIfEmpty() {
  const n = await db.players.count();
  if (n) return false;
  await db.transaction('rw', db.players, db.blueprint, db.goals, db.sessions, db.rounds, db.lessons, db.meta, async () => {
    await db.players.put({ id: PLAYER_ID, name: 'Barry Winters', handicap: '', homeClub: '', coach: 'Jack', academy: '', ambition: 'Consistent single-figure golf; a measurable development roadmap with Jack' });
    await db.blueprint.put({
      playerId: PLAYER_ID,
      swing: 'Example: neutral grip, shallower shaft in transition, hold face through impact. Priority — start line control with driver.',
      shortgame: 'Example: lower-flight chip as default; landing-spot focus. Priority — up-and-down % from 10–30 yards.',
      putting: 'Example: aim/read routine; speed control 20–40 ft. Priority — lag putting to inside 3 ft.',
      physical: 'Example: thoracic rotation mobility, single-leg stability.',
      mental: 'Example: pre-shot routine consistency; scoring plan per hole.',
      course: 'Example: club off the tee by hazard, not by distance. Attack only from the fairway.',
    });
    await db.goals.bulkAdd([
      { area: 'Driving',  metric: 'Driver club speed', unit: 'mph', baseline: 110, current: 110, target: 115, by: '2027-03-31' },
      { area: 'Driving',  metric: 'Driver smash factor (premium ball)', unit: '', baseline: 1.36, current: 1.36, target: 1.48, by: '2027-03-31' },
      { area: 'Approach', metric: 'Greens in regulation', unit: '%', baseline: 42, current: 42, target: 50, by: '2027-03-31', source: 'example' },
      { area: 'Putting',  metric: 'Putts per round', unit: '', baseline: 33, current: 33, target: 31, by: '2027-03-31', source: 'example' },
      { area: 'Scoring',  metric: 'Scoring average', unit: '', baseline: 82.6, current: 82.6, target: 79, by: '2027-06-30', source: 'example' },
    ].map(g => ({ ...g, playerId: PLAYER_ID })));
    await db.sessions.bulkAdd(trackman.map(s => ({ ...s, playerId: PLAYER_ID })));
    await db.rounds.bulkAdd([
      { date: '2026-06-20', course: 'Home course', par: 72, score: 86, fir: 6, firOf: 14, gir: 6, putts: 35, upDown: 2, upDownOf: 8, pen: 2, sgT: -2.1, sgA: -4.0, sgG: -1.8, sgP: -1.6 },
      { date: '2026-07-18', course: 'Home course', par: 72, score: 83, fir: 7, firOf: 14, gir: 7, putts: 34, upDown: 3, upDownOf: 8, pen: 1, sgT: -1.6, sgA: -3.5, sgG: -1.4, sgP: -1.2 },
      { date: '2026-08-08', course: 'Away',        par: 71, score: 84, fir: 8, firOf: 14, gir: 8, putts: 33, upDown: 4, upDownOf: 8, pen: 2, sgT: -1.2, sgA: -3.6, sgG: -1.0, sgP: -0.9 },
      { date: '2026-08-29', course: 'Home course', par: 72, score: 81, fir: 8, firOf: 14, gir: 8, putts: 33, upDown: 4, upDownOf: 7, pen: 0, sgT: -1.0, sgA: -3.0, sgG: -0.9, sgP: -0.8 },
      { date: '2026-09-13', course: 'Home course', par: 72, score: 79, fir: 9, firOf: 14, gir: 9, putts: 31, upDown: 5, upDownOf: 8, pen: 1, sgT: -0.6, sgA: -2.6, sgG: -0.6, sgP: -0.3 },
    ].map(r => ({ ...r, source: 'example', playerId: PLAYER_ID })));
    await db.lessons.bulkAdd([
      { date: '2026-08-14', focus: 'Driver start line', notes: 'Example lesson. Face 3–4° open at impact with an out-to-in path. Worked on lead-wrist flexion at the top and a feel of the club exiting left.', drills: ['Alignment-stick gate, 20 balls at 80%', 'Pump drill to P6, 3×10', 'Film 5 swings down-the-line each session'], priorities: ['Start line inside 10 yds either side', 'Keep smash ≥ 1.46'] },
      { date: '2026-09-11', focus: 'Wedge distance control', notes: 'Example lesson. Three-length system (7:30 / 9:00 / 10:30) with PW and gap wedge; carry numbers logged on TrackMan.', drills: ['Ladder drill 60–110 yds, 2 balls per number', 'Clock-system calibration fortnightly'], priorities: ['Proximity from 100 yds inside 25 ft'] },
    ].map(l => ({ ...l, source: 'example', playerId: PLAYER_ID })));
    await db.meta.put({ key: 'examples', value: true });
  });
  return true;
}
