/**
 * Starter lessons for the Academy — public YouTube videos surfaced by web search on 22 Sep 2026.
 * View counts could NOT be verified from the build environment (YouTube blocks the fetcher);
 * these are well-known channels on each topic, flagged source:'suggested' for the coach to keep or remove.
 * URLs are exactly as returned by search; titles as listed there.
 */
import { nodeId } from '../lib/academy.js';

export const STARTER_LESSONS = [
  // Strike
  { node: nodeId('strike', 'Functional vertical low point'), title: 'The Best Ball Striking Tip I\'ve Ever Heard', url: 'https://www.youtube.com/watch?v=vO4t_FCG-w0', notes: 'Low point ahead of the ball: where the club bottoms out decides strike before anything else. Watch for where the divot starts.', drills: ['Line drill: ball on a line, divot must start on the target side [Skill]', 'Towel behind the ball, 20 balls [Skill]'] },
  { node: nodeId('strike', 'Consistent face contact'), title: 'One Simple Test to INSTANTLY Improve Your Golf Strikes | Padraig Harrington', url: 'https://www.youtube.com/watch?v=3-OzwniIjR8', notes: 'Harrington on finding centre strike. Use foot spray on the face to see the pattern before changing anything.', drills: ['Foot spray on the face, 10 balls, photograph the pattern [Performance]', 'Tee-height / ball-position adjustment until the pattern centres [Skill]'] },
  { node: nodeId('strike', 'Consistent face contact'), title: 'Center face contact, impact tape / spray review', url: 'https://www.youtube.com/watch?v=mjtUQSRkZjk', notes: 'How to read impact tape and spray marks: heel, toe, high, low, and what each does to ball speed and curve.', drills: [] },
  { node: nodeId('strike', 'Functional horizontal low point'), title: 'Finding The Ground & Setup | Padraig Harrington', url: 'https://www.youtube.com/watch?v=yhw0D5H_mQU', notes: 'Setup and ground pressure that keeps the arc where it should be. Links directly to "bum on the butt line" in the blueprint.', drills: ['Step drill for pressure shift [Technique]'] },
  // Distance
  { node: nodeId('distance', 'Functional club speed'), title: '3 Proven Ways To Increase Your Clubhead Speed Instantly', url: 'https://www.youtube.com/watch?v=AdCHcf6NCX8', notes: 'Speed is not the constraint for Barry (105–114 mph), but the sequencing cues here are the same ones that protect strike.', drills: [] },
  { node: nodeId('distance', 'Functional launch'), title: 'How to Maximize Driver Distance with Trackman | Smash Factor, Launch Angle & Spin Rate Explained', url: 'https://www.youtube.com/watch?v=jjQ_-Hz60oc', notes: 'The three numbers that turn speed into carry. Compare with the Launch window chart on the TrackMan tab.', drills: ['Tee height ladder: 3 heights × 5 balls, log launch and spin [Performance]'] },
  { node: nodeId('distance', 'Functional spin'), title: 'How to Maximize Driver Distance with Trackman | Smash Factor, Launch Angle & Spin Rate Explained', url: 'https://www.youtube.com/watch?v=jjQ_-Hz60oc', notes: 'Same video — the spin section. Driver window ~2,000–3,000 rpm; strike height on the face moves spin more than most swing changes.', drills: [] },
  // Direction
  { node: nodeId('direction', 'Functional repeatable face angle'), title: 'Face Sends It, Path Bends It — The Golf Ball Flight Laws Explained | Titleist', url: 'https://www.youtube.com/watch?v=CUG9nwxjcMU', notes: 'The ball flight laws in one video. Face controls start line; face-to-path controls curve. This is the At impact diagram on the TrackMan tab.', drills: ['Start-line gate 3 yds ahead, 10 balls each way [Skill]'] },
  { node: nodeId('direction', 'Functional repeatable swing direction'), title: 'Face Sends It, Path Bends It — The Golf Ball Flight Laws Explained | Titleist', url: 'https://www.youtube.com/watch?v=CUG9nwxjcMU', notes: 'Path section. Barry\'s path swings between −1.3° and +4.1° across sessions — repeatability is the target, not a number.', drills: ['Alignment-stick exit drill [Technique]'] },
  { node: nodeId('direction', 'Functional repeatable swing plane'), title: 'Sync Your Body & Arms (99% Of Amateurs Get This Wrong) | Paddy\'s Golf Tips #46', url: 'https://www.youtube.com/watch?v=PTTEi9fh0K0', notes: 'Arms staying in front of the body — the plane holds when the sync holds.', drills: [] },
  // Skills
  { node: nodeId('skills', 'Carry distances'), title: 'Stop Chunking Your Wedges: Dan Grieve\'s Short Game Secrets', url: 'https://www.youtube.com/watch?v=spo_R5w5-A4', notes: 'Dan Grieve on wedge strike and distance. Pair with the clock-system calibration in the lesson log.', drills: ['Clock system: 7:30 / 9:00 / 10:30 with PW and GW, log carries [Performance]'] },
  // Gaining access to acquired skills
  { node: nodeId('access', 'Pre-shot routine'), title: 'Establishing a Consistent Pre-Shot Routine | Paddy\'s Golf Tips #27 | Padraig Harrington', url: 'https://www.youtube.com/watch?v=2fpe91bcHMQ', notes: 'A routine you can repeat under pressure. Build it once, score commitment 1/0 on every shot.', drills: ['Play 9 holes scoring commitment yes/no per shot [Performance]'] },
  { node: nodeId('access', 'Commitment'), title: 'Josh Nichols: Golf Mindset 101, Tournament Tips & Commitment', url: 'https://www.youtube.com/watch?v=70BBwqTbfjA', notes: 'Commitment as a trainable skill rather than a mood.', drills: [] },
  { node: nodeId('access', 'Being present'), title: 'Josh Nichols | The Mental Shift To Access Performance', url: 'https://www.youtube.com/watch?v=F8QtKzK_2DU', notes: 'Getting access to the skills you already own — the whole point of this branch of the map.', drills: [] },
  // Golf IQ
  { node: nodeId('iq', 'Strategy: knowing correct target'), title: 'The Simple Course Strategy That Instantly Lowers Your Score', url: 'https://www.youtube.com/watch?v=GXUWYyC0iOA', notes: 'Target selection from dispersion, not from the flag. Use the dispersion field on the Overview to pick real targets.', drills: [] },
  { node: nodeId('iq', 'Strategy: knowing expectation'), title: 'How Pros Play Golf. Nine Holes with Scott Fawcett (DECADE) — Course Management Tips', url: 'https://www.youtube.com/watch?v=JPmtrxpguuI', notes: 'What a good shot actually looks like from each distance. Sets expectation against Jack\'s proximity targets in the Stats branch.', drills: [] },
  { node: nodeId('iq', 'Strategy: front / back / mid pin'), title: 'Golf\'s #1 Strategist Fixes the 6 Shots You Keep Screwing Up', url: 'https://www.youtube.com/watch?v=wdBsUQG8hbk', notes: 'Pin position and where the miss must be.', drills: [] },
  { node: nodeId('iq', 'Reading the green: slopes, above or below'), title: 'AimPoint Putting Explained: Does AimPoint Work? And How To Read Greens with AimPoint', url: 'https://www.youtube.com/watch?v=oc2BxEvGjvQ', notes: 'Feel the slope with your feet, then count fingers. Works with the "is the green above or below me" question in the map.', drills: ['10 putts from 15 ft, call the break before every one, log hits [Performance]'] },
  { node: nodeId('iq', 'Reading the green: firmness and speed'), title: 'Explaining How To Read Greens | Short Game Routine You Need To Watch', url: 'https://www.youtube.com/watch?v=znusWNuknwU', notes: 'Green reading as part of a routine, not a separate act.', drills: [] },
].map(l => ({ ...l, pro: false, source: 'suggested' }));
